version: "3"

volumes:
  db-store:

services:
  lottery_app:
    build:
      context: ../
      dockerfile: ./local/Dockerfile
      args:
        - TZ=${TZ:-Asia/Tokyo}
    container_name: lottery_app
    volumes:
      - ${PROJECT_PATH}:/app
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${APP_PORT:-9000}:9000
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=lottery_db
      - DB_DATABASE=${DB_NAME:-homestead}
      - DB_USERNAME=${DB_USER:-homestead}
      - DB_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Tokyo}

    stdin_open: true
    tty: true

  lottery_db:
    image: mysql:8.0
    container_name: lottery_mysql
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/my_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${DB_NAME:-homestead}
      - MYSQL_USER=${DB_USER:-homestead}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Tokyo}

  lottery_web:
    image: nginx:stable-alpine
    container_name: lottery_nginx
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ${PROJECT_PATH}:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lottery_app
